Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -9,44 +9,40 @@ jobs:
   terraform:
     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        working-directory: terraform-homework-help-infrastructure
-
     steps:
       - name: Checkout source code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4  # Checkout your repo
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: 1.5.0
+          terraform_version: 1.5.0  # Specify the version of Terraform
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-session-name: GitHubActionsSession
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # ARN for the IAM role to assume
+          aws-region: ${{ secrets.AWS_REGION }}  # AWS region
+          role-session-name: Githubaction-aws-assumerole
           role-duration-seconds: 3600
 
       - name: Terraform Init
-        run: terraform init
+        run: terraform init  # Initialize Terraform configuration
 
       - name: Terraform Validate
-        run: terraform validate
+        run: terraform validate  # Validate Terraform configuration
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -out=tfplan
-        continue-on-error: true
+        run: terraform plan -out=tfplan  # Create Terraform execution plan
+        continue-on-error: true  # Continue even if plan fails (for subsequent check)
 
       - name: Check Terraform Plan
         run: |
           if [ ${{ steps.plan.outcome }} != "success" ]; then
             echo "Terraform plan failed"
-            exit 1
+            exit 1  # Exit if plan fails
           fi
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve tfplan
+        run: terraform apply -auto-approve tfplan  # Apply the Terraform plan
